repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8'
    hooks:
    -   id: poetry-check
    -   id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements-docs.txt"]
        verbose: true